apiVersion: v2
name: frontend-toolsapps
description: A Helm chart for Frontend ToolsApps - React + Vite + Tailwind CSS
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - frontend
  - react
  - vite
  - tailwindcss
maintainers:
  - name: ToolsApps Team
    email: contact@toolsapps.eu
sources:
  - https://github.com/st3ph31/frontend-toolsapps

