apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend-toolsapps.fullname" . }}
  labels:
    {{- include "frontend-toolsapps.labels" . | nindent 4 }}
data:
  # Configuration de l'application (si n√©cessaire)
  app.config: |
    # Configuration frontend

