{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "frontend-toolsapps.fullname" . }}
  labels:
    {{- include "frontend-toolsapps.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "frontend-toolsapps.selectorLabels" . | nindent 6 }}
{{- end }}

